config:
  clientID: "oauth2-proxy-iris"
  clientSecret: "IeN2O2ZEwlja9frukAYqf6lkMIAYV7xh"
  cookieSecure: false
  cookieName: "my-cookie"
  cookieSecret: "UmRaMTlQajM1a2ordWFYRnlJb2tjWEd2MVpCK2grOFM="
  configFile: |-
    provider = "oidc"
    oidc_issuer_url="http://10.238.154.207:31769/realms/iris"
    profile_url="http://10.238.154.207:31769/realms/iris/protocol/openid-connect/userinfo"
    validate_url="http://10.238.154.207:31769/realms/iris/protocol/openid-connect/userinfo"
    scope="iris openid email profile roles"
    pass_host_header = true
    reverse_proxy = true
    auth_logging = true
    cookie_httponly = true
    cookie_refresh = "4m"
    cookie_secure = false
    email_domains = "*"
    pass_access_token = true
    pass_authorization_header = true
    request_logging = true
    #session_store_type = "redis"
    set_authorization_header = true
    set_xauthrequest = true
    silence_ping_logging = true
    skip_provider_button = true
    skip_auth_strip_headers = false
    skip_jwt_bearer_tokens = true
    ssl_insecure_skip_verify = true
    standard_logging = true
    redirect_url="http://oauth.demo.com:31070/oauth2/callback"
    redeem_url="http://10.238.154.207:31769/realms/iris/protocol/openid-connect/token"
    upstreams = [ "static://200" ]
    #whitelist_domains = ["httpbin.foo.svc.cluster.local"]
