apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: request-keycloak-auth-iris
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgatewayiris
  jwtRules:
  - issuer: "http://10.238.154.207:31769/realms/iris"
    jwksUri: "http://10.238.154.207:31769/realms/iris/protocol/openid-connect/certs"